"""
Django settings for surat project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
for _env_candidate in [BASE_DIR / ".env", BASE_DIR.parent / ".env", Path.cwd() / ".env"]:
    if _env_candidate.exists():
        try:
            from dotenv import load_dotenv
            load_dotenv(_env_candidate, override=True)
        except Exception:
            pass
        # Direct parsing fallback to guarantee values are loaded into os.environ
        try:
            with open(_env_candidate, "r", encoding="utf-8") as _f:
                for _line in _f:
                    _line = _line.strip()
                    if _line and not _line.startswith("#") and "=" in _line:
                        _k, _v = _line.split("=", 1)
                        _k = _k.strip()
                        _v = _v.strip().strip('"').strip("'")
                        if _v:
                            os.environ[_k] = _v
        except Exception:
            pass

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r@*7_&y@m%#x3+j^&ef$l3nb6f1j)8)k_oc^pu4(e)eq9@9k0m",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_env_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [
    "suratlive.biz499.com",
    "www.suratlive.biz499.com",
    ".biz499.com",
    "biz499.com",
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "testserver",
    "*",
]
if any(_env_allowed_hosts):
    for _host in _env_allowed_hosts:
        _h = _host.strip()
        if _h and _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",

    "businesses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "businesses.middleware.EnsureSchemaMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'surat.urls'

FRONTEND_DIST = BASE_DIR / 'dist'
if not FRONTEND_DIST.exists() and (BASE_DIR.parent / 'frontend' / 'dist').exists():
    FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST] if FRONTEND_DIST.exists() else [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'surat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
_db_engine = os.environ.get("DATABASE_ENGINE", "django.db.backends.sqlite3").strip()
_db_name = os.environ.get("DATABASE_NAME", "").strip()

if _db_engine == "django.db.backends.sqlite3" or not _db_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(_db_name) if _db_name else BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': _db_name,
            'USER': os.environ.get("DATABASE_USER", "").strip(),
            'PASSWORD': os.environ.get("DATABASE_PASSWORD", "").strip(),
            'HOST': os.environ.get("DATABASE_HOST", "localhost").strip(),
            'PORT': os.environ.get("DATABASE_PORT", "5432" if "postgresql" in _db_engine else "3306").strip(),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) for collectstatic and deployment
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
# collectstatic destination directory:
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / 'staticfiles'))

STATICFILES_DIRS = [
    FRONTEND_DIST,
] if FRONTEND_DIST.exists() else []

# Storage backends for static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Email Configuration (Django 6.1 modern MAILERS reading from .env)
_email_user = os.environ.get("EMAIL_HOST_USER", "").strip()
_email_pass = os.environ.get("EMAIL_HOST_PASSWORD", "").strip().replace(" ", "")
_email_host = os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip()
_email_port = int(os.environ.get("EMAIL_PORT", 587))
_email_tls = os.environ.get("EMAIL_USE_TLS", "True").lower() in ["true", "1", "yes"]

if _email_user and _email_pass:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': _email_host,
                'port': _email_port,
                'username': _email_user,
                'password': _email_pass,
                'use_tls': _email_tls,
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    f"OnlineSurat Verification <{_email_user or 'noreply@suratlive.biz499.com'}>",
)

# CORS Configuration for React Frontend & Live Domain
_env_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
CORS_ALLOWED_ORIGINS = [
    # Production live domains
    "https://suratlive.biz499.com",
    "https://www.suratlive.biz499.com",
    "http://suratlive.biz499.com",
    "http://www.suratlive.biz499.com",
    "https://biz499.com",
    "http://biz499.com",
    # Local development hosts
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5178",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5178",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]
if any(_env_cors_origins):
    for _orig in _env_cors_origins:
        _o = _orig.strip()
        if _o and _o not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_o)

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins for live and local environments
CSRF_TRUSTED_ORIGINS = [
    "https://suratlive.biz499.com",
    "https://www.suratlive.biz499.com",
    "http://suratlive.biz499.com",
    "http://www.suratlive.biz499.com",
    "https://*.biz499.com",
    "http://*.biz499.com",
    "https://biz499.com",
    "http://biz499.com",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5178",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5178",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]

# Support SSL / HTTPS reverse proxies (e.g. Nginx, Cloudflare, Caddy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
